services:
  postgres_py:
    image: postgis/postgis:latest
    container_name: smart_waste_db_python
    environment:
      POSTGRES_USER: aybex_py
      POSTGRES_PASSWORD: password_py
      POSTGRES_DB: smart_waste_py
    ports:
      - "5434:5432"
    volumes:
      - pgdata_py:/var/lib/postgresql/data
    restart: always

  redis_py:
    image: redis:alpine
    container_name: smart_waste_redis_python
    ports:
      - "6381:6379"
    restart: always

  mosquitto_py:
    image: eclipse-mosquitto:1.6
    container_name: smart_waste_mqtt_python
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  backend:
    build:
      context: ./backend
    container_name: smart_waste_backend
    depends_on:
      - postgres_py
      - mosquitto_py
      - redis_py
    environment:
      POSTGRES_DB: smart_waste_py
      POSTGRES_USER: aybex_py
      POSTGRES_PASSWORD: password_py
      POSTGRES_HOST: postgres_py
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: smart_waste_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

volumes:
  pgdata_py: