# Generated by Django 6.0.4 on 2026-04-27 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('DRIVER', 'Chauffeur')], default='DRIVER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fill_level', models.FloatField(default=0.0)),
                ('alert_status', models.CharField(choices=[('EMPTY', 'Vide (0-50%)'), ('PARTIAL', 'Partiel (51-79%)'), ('FULL', 'Critique (80-100%)')], default='EMPTY', max_length=15)),
                ('physical_status', models.CharField(choices=[('OPERATIONAL', 'Opérationnel'), ('MAINTENANCE', 'En maintenance'), ('BROKEN', 'Hors service')], default='OPERATIONAL', max_length=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'containers',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('capacity', models.FloatField()),
                ('current_load', models.FloatField(default=0.0)),
                ('mileage', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ON_MISSION', 'En mission')], default='AVAILABLE', max_length=15)),
                ('physical_status', models.CharField(choices=[('OPERATIONAL', 'Opérationnel'), ('MAINTENANCE', 'En maintenance'), ('BROKEN', 'Hors service')], default='OPERATIONAL', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_truck', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trucks',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée')], default='PLANNED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='smart_waste_core.truck')),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('point_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_order', models.PositiveIntegerField()),
                ('is_emptied', models.BooleanField(default=False)),
                ('emptied_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_points', to='smart_waste_core.container')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_points', to='smart_waste_core.route')),
            ],
            options={
                'db_table': 'collection_points',
                'ordering': ['stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
    ]
