# Generated by Django 6.0.4 on 2026-05-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_waste_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur'), ('DRIVER', 'Chauffeur')], default='DRIVER', max_length=20),
        ),
    ]
